name: CusTele
main: net.ddns.yonatand.Main
version: 1.0
author: yonatand
commands:
   ctp:
      description: This is a demo teleportation command.
      usage: /ctp [player]
      permission: CusTele.ctp
      permission-message: You don't have the permissions to run this command.