name: CaexCore
main: net.ddns.yonatand.core.Main
version: 1.0
author: yonatand
api-version: 1.13
commands:
   tp:
      description: This teleports you to a player.
      usage: /tp [player]
      permission: CaexCore.tp
      permission-message: You don't have the permissions to run this command.
      aliases: [to]
   tphere:
      description: This teleports a player to you.
      usage: /tphere [player]
      permission: CaexCore.tphere
      permission-message: You don't have the permissions to run this command.
      aliases: [get]
   gm:
      description: set your gamemode.
      usage: /gm [0/1/2/3] [Optional username]
      permission: CaexCore.gm
      permission-message: You don't have the permissions to run this command.
      aliases: [gamemode]
   setspawn:
      description: This sets the server's spawn
      usage: /setspawn
      permission: CaexCore.setspawn
      permission-message: You don't have the permissions to run this command.
   spawn:
      description: This teleports you to the lobby
      usage: /spawn
      permission: CaexCore.spawn
      permission-message: You don't have the permissions to run this command.
      aliases: [lobby]
   addwarp:
      description: This adds a warp
      usage: /addwarp [name]
      permission: CaexCore.addwarp
      permission-message: You don't have the permissions to run this command.
      aliases: [setwarp]
   deletewarp:
      description: This deletes a warp
      usage: /deletewarp [name]
      permission: CaexCore.deletewarp
      permission-message: You don't have the permissions to run this command.
      aliases: [delwarp]
   warp:
      description: warp
      usage: /warp [name]
      permission: CaexCore.warp
      permission-message: You don't have the permissions to run this command.
   tele:
      description: test tele effect command
      usage: /tele
      permission: CaexCore.tele
      permission-message: You don't have the permissions to run this command.
   givegold:
      description: gives you special gold
      usage: /givegold [ammount]
      permission: CaexCore.givegold
      permission-message: You don't have the permissions to run this command.
   homes:
      description: shows your list of homes
      usage: /homes
      permission: CaexCore.homes
      permission-message: You don't have the permissions to run this command.
   addhome:
      description: adds a home to your homes
      usage: /home [name]
      permission: CaexCore.addhome
      permission-message: You don't have the permissions to run this command.
   deletehome:
      description: deletes a home
      usage: /deletehome [name]
      permission: CaexCore.delhome
      permission-message: You don't have the permissions to run this command.
      aliases: [delhome]
   home:
      description: teleports you to a home
      usage: /home [name]
      permission: CaexCore.home
      permission-message: You don't have the permissions to run this command.
   nick:
      description: sets your nickname
      usage: /nick [name]
      permission: CaexCore.nick
      permission-message: You don't have the permissions to run this command.
   resetnick:
      description: resets your nickname
      usage: /resetnick
      permission: CaexCore.nick
      permission-message: You don't have the permissions to run this command.
      aliases: [rnick]
   addportal:
      description: adds a portal
      usage: /addportal
      permission: CaexCore.addportal
      permission-message: You don't have the permissions to run this command.
permissions:
    CaexCore.color:
        description: gives all color perms for this plugin
        default: op
        children:
            CaexCore.color.chat:
                default: op
            CaexCore.color.sign:
                default: op
    CaexCore.*:
        description: gives all permissions for the plugin
        default: op
        children:
            CaexCore.tp:
                default: op
            CaexCore.tphere:
                default: op
            CaexCore.gm:
                default: op
            CaexCore.setspawn:
                default: op
            CaexCore.spawn:
                default: op
            CaexCore.addwarp:
                default: op
            CaexCore.deletewarp:
                default: op
            CaexCore.warp:
                default: op
            CaexCore.tele:
                default: false
            CaexCore.givegold:
                default: op
            CaexCore.homes:
                default: op
            CaexCore.addhome:
                default: op
            CaexCore.delhome:
                default: op
            CaexCore.home:
                default: op
            CaexCore.nick:
                default: op
            CaexCore.resetnick:
                default: op
    CaexCore.addportal:
        default: false
